### ISSUE TITLE
TypeScript Server Error

### ISSUE THREAD

**Issue by milesmou** [microsoft/vscode-typescript-next#129]
ERR <semantic> TypeScript Server Error (5.7.0-dev.20240912)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.addImportFromExportedSymbol (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:155834:13)
    at c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:163010:38
    at Array.forEach (<anonymous>)
    at importSymbols (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:163010:11)
    at c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162600:11
    at sameMap (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:2489:22)
    at createSignatureDeclarationFromSignature (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162594:27)
    at outputMethod (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162496:20)
    at Object.addNewNodeForMemberSymbol (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162475:9)
    at getEntryForMemberCompletion (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:165280:22)
    at createCompletionEntry (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:165120:35)
    at getCompletionEntriesFromSymbols (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:165763:19)
    at completionInfoFromData (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:164753:23)
    at Object.getCompletionsAtPosition (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:164286:24)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:150659:35)
    at IpcIOSession.getCompletions (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:192730:54)
    at completionInfo (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:191053:43)
    at c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193504:15
    at IpcIOSession.executeWithRequestId (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193493:14)
    at IpcIOSession.executeCommand (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193502:29)
    at IpcIOSession.onMessage (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193550:68)
    at process.<anonymous> (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\tsserver.js:525:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.7.0-dev.20240912)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.addImportFromExportedSymbol (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:155834:13)
    at c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:163010:38
    at Array.forEach (<anonymous>)
    at importSymbols (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:163010:11)
    at c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162600:11
    at sameMap (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:2489:22)
    at createSignatureDeclarationFromSignature (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162594:27)
    at outputMethod (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162496:20)
    at Object.addNewNodeForMemberSymbol (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:162475:9)
    at getEntryForMemberCompletion (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:165280:22)
    at createCompletionEntry (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:165120:35)
    at getCompletionEntriesFromSymbols (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:165763:19)
    at completionInfoFromData (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:164753:23)
    at Object.getCompletionsAtPosition (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:164286:24)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:150659:35)
    at IpcIOSession.getCompletions (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:192730:54)
    at completionInfo (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:191053:43)
    at c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193504:15
    at IpcIOSession.executeWithRequestId (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193493:14)
    at IpcIOSession.executeCommand (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193502:29)
    at IpcIOSession.onMessage (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\typescript.js:193550:68)
    at process.<anonymous> (c:\Users\81360\.vscode\extensions\ms-vscode.vscode-typescript-next-5.7.20240912\node_modules\typescript\lib\tsserver.js:525:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
	at n.create (d:\Applications\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:474083)
	at v.dispatchResponse (d:\Applications\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:468053)
	at v.dispatchMessage (d:\Applications\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:466851)
	at ChildProcess.<anonymous> (d:\Applications\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:466344)
	at ChildProcess.emit (node:events:519:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
