### ISSUE TITLE
No more syntax color

### ISSUE THREAD

**Issue by jujax** [microsoft/vscode-typescript-next#57]
Type: <b>Bug</b>

Since last update, there is no more colors in text editor, keyword like async, const, new etc... are displayed with default text color

Extension version: 5.0.20221116
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.19.0-23-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600U with Radeon Graphics (12 x 3102)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|14.95GB (11.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id f6ca7d88-02dc-4d5d-ac4e-a69b2ecd70ce|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by Networkzz** [comment]
Happening to me too, had to go 1 version lower in order to fix it.

**Comment by Tatanstii** [comment]
Happening to me too!!

**Comment by Yatoo2018** [comment]
Happening to me too!!

**Comment by reikrom** [comment]
```
xt-5.0.20221116/syntaxes/JavaScript.tmLanguage.json SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.t.parseRawGrammar (grammarReader.js:22:17)
    at Object.loadGrammar (TMGrammarFactory.ts:55:28)
   ```

**Comment by mjbvz** [comment]
Duplicate of #43
