### ISSUE TITLE
Error: Debug Failure. False expression InferredProject2.updateGraphWorker

### ISSUE THREAD

**Issue by malipetek** [microsoft/vscode-typescript-next#85]
Hello, I have no idea why this happened but I have had type hanging up as (loading...) in all typescript related files.
I modified some types thinking it was something I did. Then I tried on different projects and saw I am getting same error.
I now uninstalled this extension and wanted to let you know. 

Here is the image of line it points and rest of the stack trace:

<img width="794" alt="image" src="https://github.com/microsoft/vscode-typescript-next/assets/13527277/59466d72-d24f-4fa3-bc96-e8bf6bf94698">

```
 Error: Debug Failure. False expression.
        at InferredProject2.updateGraphWorker (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:174841:11)
        at InferredProject2.updateGraph (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:174700:32)
        at updateProjectIfDirty (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:176407:35)
        at InferredProject2.getLanguageService (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:174311:7)
        at IpcIOSession.getApplicableRefactors (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:182312:20)
        at getApplicableRefactors (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:180568:43)
        at /Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:182701:69
        at IpcIOSession.executeWithRequestId (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:182693:14)
        at IpcIOSession.executeCommand (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:182701:29)
        at IpcIOSession.onMessage (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:182743:51)
        at process.<anonymous> (/Users/malipetek/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230609/node_modules/typescript/lib/tsserver.js:184324:14)
        at process.emit (node:events:513:28)
        at emit (node:internal/child_process:967:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by mjbvz** [comment]
This is not a useful error message without a full log of what lead up to it. To collect this:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.


 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
